src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{
    const HEAT = [
        0=> 'electrice',
        1 => 'gaz'
    ];
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold =false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    public function __construct () {
        $this-> create_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    public function getSlug(): string
    {
        return  (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }
     public function getFormattedPrice():string
    {
      return number_format($this->price, 0, '', '');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }
     public function getHeatType():string
    {
       return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController {
  
    /**
     * @* @param  PropertyRepository $repository
      
     *  */ 
    public function index (PropertyRepository $repository) : Response {

        $property = $repository -> findLatest();
         return $this ->render('pages/home.html.twig', [
             'properties' => $property
         ]);
    }
  
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController{

   
     /**
         * @var PropertyRepository
     */
        private $repository;
        
        public function __construct(PropertyRepository $repository)
        {
            $this -> repository = $repository;
        }
     /**
     * @Route("/biens", name="proprerty.index")
     * @return Response
   
     */
    public function index() : Response 
     {
       
         $property= $this->repository ->findAllVisible();
         dump($property); 
         return $this -> render('/property/index.html.twig', [
             'current_menu' => 'properties'
         ]);
     }

      /**
     * @Route("/biens/{slug}-{id}", name="property.show" , requirements={"slug" : "[a-z0-9\-]*"})
     * @return Response
      
     */
    public function show($slug ,$id):Response
    {
      
        $property = $this -> repository->find($id);

        if($property->getSlug() !== $slug){
         return   $this->redirectToRoute('property.show',[
                'id'=> $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }
        return $this -> render('property/show.html.twig',[
            'property' => $property,
            'current_menu' => 'properties'
        ]);
    }
 

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">          
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
         <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href='{{path('home')}}'  >My Agence</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                        <a class="nav-link {% if current_menu is defined and current_menu == 'properties'  %}active {% endif %}  "    href='{{path('proprerty.index')}}'>Acheter</a>
                        </li>
                    </ul>
                </div>
             </div> 
            </nav>
                   
           

        {% block body %}{% endblock %}
   
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    </body>
</html>

templates/pages/Home.html.twig
{% extends 'base.html.twig' %}

{% block title 'Home' %}

{% block body %}
<div class='jumbotron text-center bg-gray'>
  <h1>Agence  </h1>
  <p> 
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book
  </p>
</div>
 
    <div class='container'>
      <h2>Recent Product  </h2>
      <div class='row flex'>
      {% for property in properties   %} 
          <div class='col-3'>
            <div class='card'>
              <div class='card-body'>
                <h5 class='card-title'> 
                  <a href='{{path('property.show',{id:property.id, slug:property.slug } )}} '> {{property.title}} </a>
                </h5>
                  
                <p class='card-text'> {{property.city}}( {{property.postalCode}})  </p>
                  <div class='text-primary'style='font-weight: bold;' >{{property.formattedPrice}} £ </div> 
              </div>
            </div>
          </div>
   {% endfor %} 
  
  </div>
</div>


{% endblock %}

  

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'All product' %}

{% block body %}

<div class='container mt-4'>
  <h1>All products  </h1>
 
</div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title property.title %}
{% block body %}
<div class=' pt-3 pb-3 ' style='background-color:#a2b9bc'>
  <div class='container'> 
     <div class='row'> 
    <div class='col-md-8'> </div>
  
    <div class='col-md-4'> 
    <h1> {{property.title}} </h1> 
    <h2> {{property.rooms}} rooms - {{property.surface}}  m</h2>
    <div class='text-primary' style='font-size:2rem; font-weight:bold;'>
        {{property.formattedPrice}} £
        </div>
        <a href='#' class='btn btn-primary' > Contact the Agence </a>
    </div> 
    </div> 
  </div>
 </div>
<div class='container mt-4'>

   <p>{{property.description}}  </p>
   <div class='row'>
      <div class='col-md-8'> 
       <h2>Carste </h2>
        <table class='table table-striped' >
          <tr>
            <td> Surface</td>
            <td> {{property.surface}} </td>
           </tr>
            <tr>
            <td> Number </td>
            <td> {{property.rooms}} </td>
           </tr>  
            <tr>
            <td> Rooms</td>
            <td> {{property.bedrooms}} </td>
           </tr>
            <tr>
            <td> Floor</td>
            <td> {{property.floor}} </td>
           </tr>
            <tr>
            <td> Heat</td>
            <td> {{property.HeatType}} </td>
           </tr>
        </table>
      </div>
    </div>
</div>  




{% endblock %}